/* ============================================================
   The codex. Open it mid task. It is the same reference an
   analyst keeps in a browser tab, written to be read fast.
   ============================================================ */
(function(){
"use strict";

var CODEX = [
{ c:"Standard", t:"ANSI/EIA-649", k:"eia 649 standard configuration management principles mil-std-973",
  b:["The national consensus standard for configuration management. The Department of Defense adopted it in place of MIL-STD-973, and EIA-649-1 is the version written for defense contracts.",
     "It is principle based rather than prescriptive. It tells you what has to be true, not which form to fill out. That is why every program has to tailor it in a configuration management plan, and why two programs at the same company can run CM very differently and both be compliant."]},
{ c:"Standard", t:"The five core functions", k:"five functions planning identification change status accounting audit",
  b:["1. CM planning and management. Who does what, with which tools, under which rules. Written in the program CM plan.",
     "2. Configuration identification. Selecting configuration items, numbering them, and establishing baselines.",
     "3. Configuration change management. Evaluating, classifying, approving and tracking changes to a baseline.",
     "4. Configuration status accounting. Recording and reporting what the configuration is, was, and is about to become.",
     "5. Configuration verification and audit. Proving the product matches the documentation, through FCA and PCA.",
     "If you can name these five and give a concrete example of each from your own work, you can hold most of a CM interview."]},
{ c:"Baselines", t:"Functional baseline", k:"functional baseline system specification srr sfr",
  b:["The approved system level performance requirements. Established around the system requirements review and system functional review.",
     "Once the government approves it, changes to it are Class I. This is the moment configuration control stops being an internal matter."]},
{ c:"Baselines", t:"Allocated baseline", k:"allocated baseline item performance specification pdr",
  b:["The item performance specifications, derived from the system specification and allocated down to each configuration item. Established at preliminary design review.",
     "This is where interfaces get written down, and where most of the arguments happen later."]},
{ c:"Baselines", t:"Product baseline", k:"product baseline build to drawings parts list cdr pca",
  b:["The build to configuration: released detail and assembly drawings, parts lists, process specifications, and for software the source, the build instructions and the version description.",
     "Established at critical design review. It becomes the verified product baseline after a successful physical configuration audit."]},
{ c:"Identification", t:"Configuration item", k:"ci configuration item designation",
  b:["An item designated for separate configuration management because of its criticality, its interfaces, or its support needs. A configuration item carries its own specification and its own baseline.",
     "Designating too many drowns a program in paperwork. Designating too few means the ones that matter are not controlled. The selection itself is an engineering judgment, and it belongs in the CM plan."]},
{ c:"Identification", t:"Form, fit and function", k:"fff form fit function interchangeability",
  b:["Form is the physical characteristics: size, shape, mass, finish. Fit is the ability to interface with other items. Function is what the item does and how well.",
     "FFF is the test for interchangeability, and interchangeability is the test for whether a change needs a new part number."]},
{ c:"Identification", t:"When a new part number is required", k:"part number new pn revision interchangeable one way",
  b:["Revise in place, same part number, when the changed item is fully interchangeable with what it replaces in every application.",
     "Assign a new part number when the changed item is not interchangeable in all applications.",
     "One way interchangeability is when the new item can be used in place of the old but the old cannot be used in place of the new. That takes a new number too, with the relationship recorded so nobody installs the old one where the new one is required.",
     "Never reuse a part number for an item that is not interchangeable with the one that number already means. That single rule prevents more field failures than any other rule in CM."]},
{ c:"Identification", t:"Revision letters", k:"revision letter sequence asme y14.35 forbidden i o q s x z",
  b:["Revisions advance one letter at a time: A, B, C, D, E, F, G, H, J, K, L, M, N, P, R, T, U, V, W, Y, then AA, AB and so on.",
     "I, O, Q, S, X and Z are not used, because on a print they read as numerals or as each other.",
     "A gap in the sequence is worth stopping for. It usually means a revision was released somewhere the vault does not know about."]},
{ c:"Change", t:"Class I change", k:"class 1 class i major change government approval",
  b:["A change that affects an approved baseline in a way the government controls. Any one of these makes it Class I:",
     "Form, fit or function of a configuration item under government control; a released interface; safety; weight, balance or moment of inertia beyond the specified limit; specified performance, reliability or maintainability; contract cost, price or fee; contract delivery schedule or a milestone; government furnished equipment; delivered operation, maintenance or training manuals; approved qualification or acceptance test requirements; interchangeability; sources on a source control drawing; retrofit of delivered units.",
     "A Class I change is not authorized until the contracting officer approves it. A contractor board can approve it for submittal. It cannot approve it for implementation."]},
{ c:"Change", t:"Class II change", k:"class 2 class ii minor change concurrence classification",
  b:["Everything that is not Class I. Typically drafting and editorial corrections, internal manufacturing process changes that leave the released design alone, and supplier part number updates for an identical item.",
     "Class II changes are approved by the contractor board, and the government representative concurs in the classification. That concurrence is about whether you called the class correctly, not about whether the change is a good idea."]},
{ c:"Change", t:"ECP priority", k:"emergency urgent routine priority ecp",
  b:["Emergency: a safety condition likely to cause serious injury or major damage, or a condition that has stopped production.",
     "Urgent: a potentially hazardous condition, or a change that has to move now to hold a milestone or capture a benefit that expires.",
     "Routine: everything else, through the normal board cycle.",
     "Priority is about how fast it moves. Class is about who approves it. They are independent, and people mix them up constantly."]},
{ c:"Change", t:"Deviation and waiver", k:"rfd rfw deviation waiver variance before after manufacture",
  b:["A deviation is authorization, granted before manufacture, to depart from a requirement for a specific number of units or a specific period.",
     "A waiver is authorization to accept an item that already departs from a requirement but is still considered suitable for use.",
     "The whole distinction is timing. Before the fact is a deviation. After the fact is a waiver.",
     "Neither one changes the requirement. If the requirement itself needs to change permanently, that is an engineering change, not a variance.",
     "EIA-649 folds both under the single word variance. DoD contracts still use RFD and RFW, so know both vocabularies."]},
{ c:"Change", t:"Notice of revision", k:"nor notice of revision",
  b:["The document that tells a design activity to change a drawing or associated list to reflect an approved engineering change. It travels with the ECP and it is how the approved change actually reaches the technical data."]},
{ c:"Change", t:"Effectivity", k:"effectivity serial number retrofit cut in",
  b:["Effectivity is the answer to which units get this change. A serial number range, a lot, a date, or a build label for software.",
     "Effectivity that reaches units already delivered and accepted needs retrofit direction. Quietly changing the configuration of hardware the customer already owns is not a thing you can do.",
     "A blank effectivity field means manufacturing decides, and manufacturing should never be the one deciding."]},
{ c:"Change", t:"Change control board", k:"ccb board disposition quorum minutes",
  b:["The cross functional body that dispositions changes against a baseline. Engineering, quality, manufacturing, safety, contracts, program management, software, and configuration management running the meeting.",
     "Dispositions: approve for implementation, approve for submittal to the government, approve with conditions, defer pending data, disapprove, return to the originator.",
     "Deferring is a real answer. A board that never defers is a board that is not reading the packages."]},
{ c:"Status accounting", t:"Configuration status accounting", k:"csa status accounting as built record report",
  b:["The record of what the configuration is, what it was at any past point, and what changes are pending against it.",
     "The question CSA exists to answer is: what exactly is serial number seven, as it sits, and how did it get that way.",
     "Working a status accounting question: take the changes released on or before the date asked, keep the ones whose effectivity covers the unit, add any retrofit worked by that date, and read off the highest revision among them. Answer the date you were asked about, not today."]},
{ c:"Audit", t:"Functional configuration audit", k:"fca functional audit verification test requirements",
  b:["Verifies that the configuration item has met the requirements in its specification. The evidence is test data, analysis, demonstration and inspection records.",
     "Typical findings: a requirement with no verification method, a test run to a superseded procedure, a result outside the limit recorded as a pass, open discrepancy reports at audit, requirements with no trace to a test case."]},
{ c:"Audit", t:"Physical configuration audit", k:"pca physical audit as built drawings product baseline",
  b:["Verifies that the item as built matches the technical documentation. The evidence is the as built configuration list against the released drawings and parts lists.",
     "Typical findings: an as built list at an older revision than the one effective on the unit, a wrong dash number installed, nameplate marking that disagrees with the title block, missing serialized traceability, a waiver in effect with no reference in the as built record.",
     "A successful PCA is what establishes the verified product baseline. In practice FCA and PCA are often run together, and the scope distinction still decides which audit a finding lands in."]},
{ c:"Data management", t:"CDRL", k:"cdrl contract data requirements list dd form 1423 did",
  b:["The Contract Data Requirements List. Each line item is one deliverable, tied to a data item description that specifies its content and format, with a due date, a distribution list and whether the government approves it or receives it for information.",
     "A CDRL line item is a contract requirement. Missing one is a contract delinquency, and it is one of the few configuration and data management numbers a program manager watches every week."]},
{ c:"Data management", t:"SDRL", k:"sdrl subcontractor data requirements list flow down",
  b:["The same idea, flowed down to a subcontractor. Your CDRL obligations become their SDRL obligations, and if the flow down is wrong you will be delinquent on data you never had the right to demand.",
     "Keep contracts on the thread. The subcontract is the only leverage that exists."]},
{ c:"Data management", t:"Data item description", k:"did data item description format content",
  b:["The specification for a deliverable: what goes in it and how it is arranged. Cite the wrong one and the customer can reject the document on format alone, without ever reading the content.",
     "The numbers in this simulator follow the real DI-XXXX-nnnnn pattern and several are drawn from real DIDs, but treat the specific numbers here as representative rather than as a lookup table. Check the real index before citing one on a real program."]},
{ c:"Data management", t:"Distribution statements and markings", k:"distribution statement classification portion marking",
  b:["Every controlled technical document carries a distribution statement. Classified deliverables carry portion markings as well as an overall marking, so a reader knows what they can extract.",
     "A missing marking is not a formatting comment. It is the reason a document cannot leave the building."]},
{ c:"Tools", t:"EPDM and the vault", k:"epdm pdm plm windchill enovia vault release",
  b:["The enterprise product data management system is the single source of truth for released engineering data: drawings, models, parts lists, specifications and software release packages. It enforces lifecycle states, revision control and electronic approval routing.",
     "In industry these are built on PLM platforms such as PTC Windchill or Dassault ENOVIA. The specific tool matters less than what it enforces.",
     "A file on a shared drive is not a released document. That sentence is most of the job."]},
{ c:"Tools", t:"The rest of the toolchain", k:"jira confluence sharepoint teams access database",
  b:["Jira for change board action items and defect workflow. Confluence for procedures and baseline definitions. SharePoint for board libraries, accounting logs and CDRL schedules. Teams for the boards themselves.",
     "And nearly every program has at least one Microsoft Access database somebody built in 2009 that holds a legacy cross reference nobody has migrated. Learning to query it is a real and unglamorous skill."]},
{ c:"Practice", t:"What a release audit actually checks", k:"release audit checklist package review discrepancy",
  b:["Revision sequence and legality. Signatures: every required discipline, dated after the change request, and the checker is not the preparer.",
     "Classification against the impact worksheet, and for Class I, a government approval reference.",
     "Effectivity: valid, achievable, and honest about delivered units.",
     "Consistency: title block against the parts list, sheet count against the package, references at their released revisions.",
     "Completeness: interface documents when an interface moved, a CDRL citation when it is a deliverable, a build label when it is software, a baseline identified.",
     "The audit is not about catching people. It is about the fact that the vault will accept whatever you release, forever."]},
{ c:"Practice", t:"Escapes", k:"escape field failure missed defect consequence",
  b:["An escape is a defect that got past the control and was found later, usually by hardware. Escapes are the metric that matters, because they are the only one that cannot be improved by working faster.",
     "When one surfaces, the order is: establish what is actually out there, tell the customer honestly including what you cannot establish, then close the hole that let it through. Skipping the third step guarantees a fourth conversation."]},
{ c:"Career", t:"The ladder", k:"e1 e2 e3 e4 e5 associate senior staff levels salary",
  b:["E1 Associate: task level execution. Change packages, CCB minutes, baseline tracking, CDRL loading.",
     "E2: subsystem baseline ownership, Class I and II classification, board facilitation.",
     "E3 Senior: writes the CM plan, tailors the standard, leads FCA and PCA, owns subcontract data.",
     "E4 Staff: architecture. Baselines across MBSE and PLM, digital thread across sites, primary CM interface to the government program office.",
     "E5 Senior Staff: policy for the business area, toolchain strategy, multi site harmonization, executive risk advice.",
     "The shift from E2 to E3 is the real one. Below it you execute a process. Above it you decide what the process is."]},
{ c:"Career", t:"Clearance", k:"clearance ts sci scif security investigation polygraph",
  b:["National security space work generally requires US citizenship and the ability to obtain and hold a Top Secret clearance with sensitive compartmented information access.",
     "The process includes a background investigation, a financial review, and for some programs a counterintelligence polygraph. It takes months. Programs hire people who are eligible and wait.",
     "Practically, a chunk of the baseline lives inside a SCIF and does not come out, which shapes how the day is structured more than most people expect."]},
{ c:"Career", t:"Questions that come up in the interview", k:"interview questions preparation",
  b:["Name the five core functions of EIA-649 and give an example of each.",
     "What makes a change Class I rather than Class II, and who approves each.",
     "Difference between a deviation and a waiver.",
     "What is the difference between an FCA and a PCA, and what establishes the verified product baseline.",
     "When does a change require a new part number.",
     "Walk me through what you would check before releasing a change package.",
     "How would you answer a customer asking for the as built configuration of a specific serial number.",
     "Tell me about a time you found a problem in someone else's work and how you handled it. That last one is not about CM and it is the one people fail."]},
{ c:"Vocabulary", t:"Terms worth knowing cold", k:"glossary terms vocabulary acronyms",
  b:["ECP engineering change proposal. ECN or ECO, the notice that implements it. NOR notice of revision. RFD request for deviation. RFW request for waiver.",
     "CI configuration item. CSCI computer software configuration item. SCD source control drawing. ACL as built configuration list.",
     "FCA and PCA, the two audits. CSA configuration status accounting. CMP configuration management plan.",
     "CDRL and SDRL, the deliverable lists. DID data item description. CLIN contract line item number.",
     "CAGE code, the five character identifier for a design activity or supplier. FFF form fit and function. MRB material review board. DMSMS diminishing manufacturing sources and material shortages."]}
];

/* ---------------- promotion boards ---------------- */
var BOARDS = {
  2: { title:"Promotion board: E1 to E2", panel:["whitlock","raghu","fenwick"],
    qs:[
      { q:"You are handed a change that moves a connector half an inch to improve technician access. The mating bracket is unchanged. How do you classify it?",
        o:["Class I. Moving a connector changes the physical interface, which is fit","Class II. It is an access improvement with no requirement change",
           "Class II, unless the harness has to be re routed","It depends on whether the program office cares"], a:0,
        w:"Fit is physical interface. Moving a connector changes it, whether or not the harness happens to reach today." },
      { q:"A package comes to you with the proposed revision two letters past the current one. What is the first thing you do?",
        o:["Stop and find out what happened to the revision in between","Correct it to the next letter and release",
           "Release it, the letter is administrative","Ask the drafter to explain in the change notice"], a:0,
        w:"A gap usually means a revision exists that the vault does not know about. Fixing the letter without finding the missing revision hides the actual problem." },
      { q:"What does a blank effectivity field on a hardware change mean in practice?",
        o:["Manufacturing decides which units get it","It applies to all units","It applies to no units until filled in","It applies to the next assembly"], a:0,
        w:"That is why it is a hard stop. Effectivity is not a formality, it is the instruction." },
      { q:"The customer asks what revision serial number six is built to. Where does the answer come from?",
        o:["The change notices released by that date whose effectivity covers that unit, plus any retrofit worked by then","The current released revision of the drawing",
           "The revision on the drawing in the unit's travelers","The last change notice released"], a:0,
        w:"Status accounting is arithmetic on effectivity and dates. The current revision is the answer to a different question." }
    ] },
  3: { title:"Promotion board: E2 to E3", panel:["whitlock","salk","achebe"],
    qs:[
      { q:"A supplier's item is discontinued. The replacement is dimensionally identical and meets every electrical requirement, but has not completed radiation qualification for one of the two applications. What happens to the part number?",
        o:["New part number. It is not interchangeable in all applications, and the old number stays alive for the qualified application",
           "Revise in place, the item is dimensionally identical","New part number and supersede the old one",
           "No change until qualification completes"], a:0,
        w:"Interchangeable in all applications is the test. One application short means not interchangeable, and the old item is still required where it is qualified." },
      { q:"Your board approves a Class I change that the contracting officer has not yet acted on. What did the board just authorize?",
        o:["Submittal of the change to the government, not implementation","Implementation, since the board has authority over the product baseline",
           "Implementation on units not yet started","Nothing, the board cannot act before the government does"], a:0,
        w:"A contractor board can approve a Class I change for submittal. Only the contracting officer authorizes implementation." },
      { q:"During an FCA you find that a unit's nameplate part number disagrees with the drawing title block. What do you do with it?",
        o:["Record it, and write the finding against the PCA where it belongs","Write it as an FCA finding, a finding is a finding",
           "Ignore it, it is outside the audit scope","Have it corrected on the spot and move on"], a:0,
        w:"Physical build against technical data is PCA scope. In practice the audits are often run together, and the finding still belongs to the right list." },
      { q:"A new contract cites EIA-649 with no tailoring for a small risk reduction effort. What goes in the CM plan?",
        o:["Tailoring: fewer configuration items, a lightweight board, full identification and status accounting, approved with the plan",
           "The full enterprise process, since the standard was cited without tailoring",
           "A minimal plan, with details handled as they arise",
           "A request to remove the CM requirement given the program size"], a:0,
        w:"The standard is principle based so it can scale. What shrinks is the ceremony, never the identification or the record." }
    ] },
  4: { title:"Promotion board: E3 to E4", panel:["achebe","salk","whitlock"],
    qs:[
      { q:"Your CAD models carry product manufacturing information and the shop works from manually derived two dimensional drawings. The two now disagree. What is the fix?",
        o:["Declare one authoritative in the CM plan, make the other derived and automatically regenerated, and reconcile the existing disagreements",
           "Require engineering to update both at each release","Treat the model as reference and keep the drawing authoritative, informally",
           "Escalate to the customer for direction"], a:0,
        w:"A digital thread is a decision about which artifact is authoritative, written down, not a tool purchase." },
      { q:"Hardware is being built on both sides of an interface whose control document has been at draft for seven months. What do you do first?",
        o:["Stop releasing against the draft and put the exposure in the risk register in writing, then get a joint board with a named government owner",
           "Keep releasing and reconcile at integration","Baseline your side and notify the partner",
           "Get the chief engineers to sign an informal agreement"], a:0,
        w:"An unbaselined interface with hardware moving against it is the highest consequence configuration risk on any program. Make it visible to the people who can fund the fix." },
      { q:"Four programs at one site each change a shared avionics module through their own board. How should governance be arranged?",
        o:["One board for the shared item with the programs as members, program boards retained for program unique items",
           "One enterprise board for everything","Leave the boards and add a coordination meeting",
           "Fork the module into program unique part numbers"], a:0,
        w:"Governance follows the item, not the organization chart." },
      { q:"The government program office wants live read access to your product data environment instead of monthly reports. What is the right answer?",
        o:["Scoped access to this program's data, with a written agreement on what counts as released, and the contractual report retained as the deliverable of record",
           "Decline, the reports are the contract deliverable","Grant broad access, they are the customer",
           "Grant access and stop producing the report"], a:0,
        w:"Access is good. Access without a boundary and without an agreement on what is authoritative produces a customer reacting to work in progress." }
    ] },
  5: { title:"Promotion board: E4 to E5", panel:["achebe","fenwick","salk"],
    qs:[
      { q:"A twenty year old product data system serves four sites, two heavily customized, one supporting a program that will be in sustainment for fifteen more years. What is the migration strategy?",
        o:["Enterprise target, new starts migrate first, the legacy program stays with a defined escrow and a retirement date tied to the program, customization retirement funded explicitly",
           "Migrate all four sites simultaneously to force convergence","Keep the old system and modernize around it",
           "Let each site choose its own path"], a:0,
        w:"Nobody finishes a big bang PLM migration on schedule. Sequencing by program lifecycle is the version that finishes." },
      { q:"A field failure traces to a four year old effectivity error. Eight units were built to a configuration with no record. What is the first obligation?",
        o:["Reconstruct the actual as built configuration of all eight from manufacturing and inspection records, and report the reconstruction with its uncertainty",
           "Correct the effectivity record to what it should have been","Retrofit all eight to the current configuration",
           "Report the failure and handle the record gap internally"], a:0,
        w:"Know what is out there, say so honestly including what you cannot establish, then close the hole. In that order." },
      { q:"A vice president asks for one number that says whether the baseline is under control.",
        o:["Give a small set that pulls in different directions: change aging, release cycle time, escapes after release, delinquent data items",
           "Open change count","On time release percentage","Tell him it cannot be reduced to a chart"], a:0,
        w:"A single number gets optimized. Four that trade against each other are much harder to fake." },
      { q:"What is the strongest argument for tailoring EIA-649 rather than adopting a prescriptive standard verbatim?",
        o:["The principles hold at every scale while the ceremony must not, and tailoring approved in the plan is what makes the scaling legitimate rather than convenient",
           "Tailoring reduces cost","Prescriptive standards are obsolete",
           "Customers prefer tailored plans"], a:0,
        w:"Cost reduction is a consequence. The reason is that a control nobody can execute at the program's scale stops being executed at all." }
    ] }
};

window.BCX = { CODEX:CODEX, BOARDS:BOARDS };
})();
